# server:
#   port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuration of RabbitMQ and Apache Kafka for automatic configuration refreshing
# of Config Server clients.
spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
  jmx:
    enabled: true
#  rabbitmq:
#    host: rabbit.tacocloud.com
#    port: 5672
#    username: tacocloud
#    password: s3cr3t
  kafka:
    bootstrap-servers:
    - kafka.tacocloud.com:9092
    - kafka.tacocloud.com:9093
    - kafka.tacocloud.com:9094

# ---
# spring:
#   profiles: production

# server:
#   port: 8080

# eureka:
#   client:
#     service-url:
#       defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/

management:
  endpoints:
    jmx:
      exposure:
        include: health, info, beans, conditions, env, config-props, mappings, loggers, httptrace, threaddump, heapdump, metrics
    web:
      exposure:
        include: refresh, hystrix.stream, health, info, beans, conditions, env, config-props, mappings, loggers, httptrace, threaddump, heapdump, metrics, notes
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
  info:
    git:
      mode: full
