server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ---
# spring:
#   profiles: production

# server:
#   port: 8080

# eureka:
#   client:
#     service-url:
#       defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/
