# server:
#   port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuration of RabbitMQ and Apache Kafka for automatic configuration refreshing
# of Config Server clients.
spring:
#  rabbitmq:
#    host: rabbit.tacocloud.com
#    port: 5672
#    username: tacocloud
#    password: s3cr3t
  kafka:
    bootstrap-servers:
    - kafka.tacocloud.com:9092
    - kafka.tacocloud.com:9093
    - kafka.tacocloud.com:9094

# ---
# spring:
#   profiles: production

# server:
#   port: 8080

# eureka:
#   client:
#     service-url:
#       defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, hystrix.stream, health, info

info:
  contact:
    email: support@tacocloud.com
    phone: 822-625-6831
